export const en = {
  userInterface: {
    welcome: 'Welcome',
    aspiration: 'Aspiration',
    flows: 'Flows',
    dust: 'Dust',
    H2O: 'H2O 14790',
    home: 'Home',
    measurements: 'Measurements',
    gasAnalyzerCheck: 'Gas Analyzer Check',
    utilities: 'Utilities',
    equipmentBase: 'Equipment Base',
    changeLanguage: 'Change language',
    polish: 'Polish',
    english: 'English',
    settings: 'Settings',
  },
  commonDataForm: {
    date: 'Date',
    dummyName: 'John Doe',
    arrivalTime: 'Time of arrival',
    measurementRequestor: 'Principal',
    emissionSource: 'Emmission source',
    pipeCrossSectionType: 'Pipe cross section type',
    staffResponsibleForMeasurement: 'Staff carrying out measurements',
    nameAndSurname: 'Name and surname',
    temperature: 'Ambient temperature',
    pressure: 'Atmospheric pressure',
  },
  pipeCrossSectionTypes: {
    ROUND: 'Round',
    RECTANGULAR: 'Rectangular',
  },
  dustScreen: {
    measurementNumber: 'Measurement no.',
    numberOfMeasurements: 'Number of Measurements',
    selectedEndType: 'Selected End Type',
    measurementStartTime: 'Start Time',
    aspirationTime: 'Aspiration Time',
    aspiratedVolume: 'Aspirated Volume',
    filterType: 'Filter Type',
    water: 'Water',
  },
  aspirationScreen: {
    date: 'Date',
    arrivalTime: 'Time of Arrival',
    measurementNumber: 'Measurement no.',
    compoundName: 'Compound Name',
    leakTightnessTest: 'Leak-tightness Test - Flow',
    aspiratorFlow: 'Aspirator flow',
    aspiratedVolume: 'Aspirated Volume',
    initialVolume: 'Initial Volume',
    sampleId: 'Sample ID number',
    compoundType: 'Sample Type',
  },
};
