export const pl = {
  userInterface: {
    welcome: 'Witaj',
    aspiration: 'Aspiracja',
    flows: 'Przepływy',
    dust: 'Pyły',
    H2O: 'H2O 14790',
    home: 'Strona główna',
    measurements: 'Pomiary',
    gasAnalyzerCheck: 'Sprawdzenie analizatora gazu',
    utilities: 'Pomocnicze',
    equipmentBase: 'Baza sprzętu',
    changeLanguage: 'Zmień język',
    polish: 'Polski',
    english: 'Angielski',
    settings: 'Ustawienia',
  },
  commonDataForm: {
    date: 'Data',
    arrivalTime: 'Godzina przyjazdu',
    measurementRequestor: 'Zleceniodawca',
    emissionSource: 'Źródło emisji',
    pipeCrossSectionType: 'Rodzaj przewodu',
    staffResponsibleForMeasurement: 'Personel biorący udział w pomiarach',
    temperature: 'Temperatura otoczenia',
    pressure: 'Ciśnienie atmosferyczne',
  },
};
