export const pl = {
  userInterface: {
    welcome: 'Witaj',
    aspiration: 'Aspiracja',
    flows: 'Przepływy',
    dust: 'Pyły',
    H2O: 'H2O 14790',
    home: 'Strona główna',
    measurements: 'Pomiary',
    gasAnalyzerCheck: 'Sprawdzenie analizatora gazu',
    settings: 'Ustawienia',
    utilities: 'Pomocnicze',
    equipmentBase: 'Baza sprzętu',
    changeLanguage: 'Zmień język',
    polish: 'Polski',
    english: 'Angielski',
    language: 'Język',
  },
  commonDataForm: {
    dummyName: 'Jan Kowalski',
    date: 'Data',
    arrivalTime: 'Godzina przyjazdu',
    measurementRequestor: 'Zleceniodawca',
    emissionSource: 'Źródło emisji',
    pipeCrossSectionType: 'Rodzaj przewodu',
    staffResponsibleForMeasurement: 'Personel wykonujący pomiary',
    nameAndSurname: 'Imię i nazwisko',
    temperature: 'Temperatura otoczenia',
    pressure: 'Ciśnienie atmosferyczne',
  },
  pipeCrossSectionTypes: {
    ROUND: 'Okrągły',
    RECTANGULAR: 'Prostokątny',
  },
  // Screen-specific translations
  dustScreen: {
    measurementNumber: 'Numer pomiaru',
    numberOfMeasurements: 'Ilość pomiarów',
    selectedEndDiameter: 'Dobrana końcówka',
    measurementStartTime: 'Godzina rozpoczęcia',
    aspirationTime: 'Czas aspiracji',
    aspiratedVolume: 'Objętość zaaspirowana',
    filterType: 'Filtr',
    water: 'Woda',
  },
  aspirationScreen: {
    date: 'Data',
    arrivalTime: 'Godzina przyjazdu',
    measurementNumber: 'Numer pomiaru',
    compoundName: 'Rodzaj próbki',
    leakTightnessTest: 'Próba szczelności - przepływ',
    aspiratorFlow: 'Przepływ przez aspirator',
    aspiratedVolume: 'Objętość zaaspirowana',
    initialVolume: 'Objętość początkowa roztworu',
    sampleId: 'Nr identyfikacyjny próbki',
    compoundType: 'Rodzaj próbki',
    loadFromStorage: 'Wczytaj dane z pliku',
  },
  h20Screen: {
    arrivalTime: 'Godzina przyjazdu',
    measurementNumber: 'Numer pomiaru',
    // TODO
    leakTightnessTest: 'Próba szczelności',
    aspiratorFlow: 'Przepływ przez aspirator',
    aspiratedVolume: 'Objętość zaaspirowana',
    initialMass: 'Masa początkowa',
    massAfterMeasurement: 'Masa końcowa',
    scrubberNumber: 'Numer płuczki',
  },
  flowsScreen: {
    pipeCrossSection: 'Przekrój przewodu',
    numberOfSpigots: 'Ilość osi pomiarowych',
    numberOfPoints: 'Ilość punktów na osi',
    width: 'Szerokość',
    height: 'Wysokość',
    pipeDiameter: 'Średnica przewodu',
    dynamicPressure: 'Ciśnienie dynamiczne',
    staticPressure: 'Ciśnienie statyczne',
    temperature: 'Temperatura',
    angle: 'Kąt',
    axisNumber: 'Numer osi pomiarowej',
    pointOnAxis: 'Punkt na osi',
  },
  utilitiesScreen: {
    utilities: 'Pomocnicze',
    measurementDuration: 'Czas trwania pomiaru',
    breakTime: 'Przerwa między pomiarami',
    startingHour: 'Czas rozpoczęcia pierwszego pomiaru',
  },
};
